import { RatingMap, FlagMap } from './types';

export const DEFAULT_MAPS = {
    ratings: {
        colors1: {
                 symbols: ["🔴",  "🟠",   "🟡",   "🟢",        "🔵",        "🟣"],
            descriptions: ["Fail", "Fair", "Good", "Very Good", "Excellent", "Superior"]
        },
        digitsOpen: {
            symbols: ["➀", "➁", "➂", "➃", "➄", "➅", "➆", "➇", "➈", "➉"],
            descriptions: Array.from({length: 10}, (_, i) => `Level ${i + 1}`)
        },
        digitsFilled: {
            symbols: ["➊","➋","➌","➍","➎","➏","➐","➑","➒","➓"],
            descriptions: Array.from({length: 10}, (_, i) => `Level ${i + 1}`)
        },
        moonPhases: {
            symbols: ["🌑", "🌒", "🌓", "🌔", "🌕"],
            descriptions: ["New", "Waxing Crescent", "First Quarter", "Waxing Gibbous", "Full"]
        }
    } as Record<string, RatingMap>,
    flags: {
        "Activity type": {
            flags: [
                ["🏯", "Administration"],
                ["🔮", "Informatics"],
                ["📜", "Literature"],
                ["🔱", "Manuscripting"],
                ["🛠️", "System"],
                ["🛞", "Other"],
            ]
        },
        "Commitment type": {
            flags: [
                ["🚀", "Goal: aspirational"],
                ["🎯", "Goal: committed"],
                ["📅", "Due"],
                ["⏳", "Scheduled"],
                ["🏁", "Get started"],
                ["📈", "Make progress"],
                ["🦬", "Yak shaving"],
                ["🍰", "Reward"],
                ["🌀", "Unplanned"],
                ["❗", "Should have"],
            ]
        },
        "Outcome type": {
            flags: [
                ["🏆", "Championic"],
                ["🏅", "Heroic"],
                ["✅", "Success"],
                ["🪜", "Made progress"],
                ["🐂", "Shorn yaks"],
                ["⌛", "Clocked in the time"],
                ["🚧", "Incomplete"],
                ["⏩", "Forwarded"],
                ["❎", "Canceled"],
                ["⛔", "Blocked"],
                ["📦", "Boxed"],
                ["🚩", "Failed"],
                ["👻", "Ghosts"],
                ["👺", "Goblins"],
                ["👹", "Ogres"],
            ]
        },
        "Alphanumerics": {
            flags: [
                // ["❶", "1"],
                // ["❷", "2"],
                // ["❸", "3"],
                // ["❹", "4"],
                // ["❺", "5"],
                // ["❻", "6"],
                // ["❼", "7"],
                // ["❽", "8"],
                // ["❾", "9"],
                // ["❿", "10"],
                // ["①", "1"],
                // ["②", "2"],
                // ["③", "3"],
                // ["④", "4"],
                // ["⑤", "5"],
                // ["⑥", "6"],
                // ["⑦", "7"],
                // ["⑧", "8"],
                // ["⑨", "9"],
                // ["⑩", "10"],
                // ["⑪", "11"],
                // ["⑫", "12"],
                // ["⑬", "13"],
                // ["⑭", "14"],
                // ["⑮", "15"],
                // ["⑯", "16"],
                // ["⑰", "17"],
                // ["⑱", "18"],
                // ["⑲", "19"],
                // ["⑳", "20"],
                // ["⓿", "0"],
                ["①", "1"],
                ["②", "2"],
                ["③", "3"],
                ["④", "4"],
                ["⑤", "5"],
                ["⑥", "6"],
                ["⑦", "7"],
                ["⑧", "8"],
                ["⑨", "9"],
                ["⑩", "10"],
                ["⑪", "11"],
                ["⑫", "12"],
                ["⑬", "13"],
                ["⑭", "14"],
                ["⑮", "15"],
                ["⑯", "16"],
                ["⑰", "17"],
                ["⑱", "18"],
                ["⑲", "19"],
                ["⑳", "20"],
                // ["⑴", "(1)"],
                // ["⑵", "(2)"],
                // ["⑶", "(3)"],
                // ["⑷", "(4)"],
                // ["⑸", "(5)"],
                // ["⑹", "(6)"],
                // ["⑺", "(7)"],
                // ["⑻", "(8)"],
                // ["⑼", "(9)"],
                // ["⑽", "(10)"],
                // ["⑾", "(11)"],
                // ["⑿", "(12)"],
                // ["⒀", "(13)"],
                // ["⒁", "(14)"],
                // ["⒂", "(15)"],
                // ["⒃", "(16)"],
                // ["⒄", "(17)"],
                // ["⒅", "(18)"],
                // ["⒆", "(19)"],
                // ["⒇", "(20)"],
                // ["⒈", "1."],
                // ["⒉", "2."],
                // ["⒊", "3."],
                // ["⒋", "4."],
                // ["⒌", "5."],
                // ["⒍", "6."],
                // ["⒎", "7."],
                // ["⒏", "8."],
                // ["⒐", "9."],
                // ["⒑", "10."],
                // ["⒒", "11."],
                // ["⒓", "12."],
                // ["⒔", "13."],
                // ["⒕", "14."],
                // ["⒖", "15."],
                // ["⒗", "16."],
                // ["⒘", "17."],
                // ["⒙", "18."],
                // ["⒚", "19."],
                // ["⒛", "20."],
                // ["⒜", "a"],
                // ["⒝", "b"],
                // ["⒞", "c"],
                // ["⒟", "d"],
                // ["⒠", "e"],
                // ["⒡", "f"],
                // ["⒢", "g"],
                // ["⒣", "h"],
                // ["⒤", "i"],
                // ["⒥", "j"],
                // ["⒦", "k"],
                // ["⒧", "l"],
                // ["⒨", "m"],
                // ["⒩", "n"],
                // ["⒪", "o"],
                // ["⒫", "p"],
                // ["⒬", "q"],
                // ["⒭", "r"],
                // ["⒮", "s"],
                // ["⒯", "t"],
                // ["⒰", "u"],
                // ["⒱", "v"],
                // ["⒲", "w"],
                // ["⒳", "x"],
                // ["⒴", "y"],
                // ["⒵", "z"],
                ["Ⓐ", "A"],
                ["Ⓑ", "B"],
                ["Ⓒ", "C"],
                ["Ⓓ", "D"],
                ["Ⓔ", "E"],
                ["Ⓕ", "F"],
                ["Ⓖ", "G"],
                ["Ⓗ", "H"],
                ["Ⓘ", "I"],
                ["Ⓙ", "J"],
                ["Ⓚ", "K"],
                ["Ⓛ", "L"],
                ["Ⓜ", "M"],
                ["Ⓝ", "N"],
                ["Ⓞ", "O"],
                ["Ⓟ", "P"],
                ["Ⓠ", "Q"],
                ["Ⓡ", "R"],
                ["Ⓢ", "S"],
                ["Ⓣ", "T"],
                ["Ⓤ", "U"],
                ["Ⓥ", "V"],
                ["Ⓦ", "W"],
                ["Ⓧ", "X"],
                ["Ⓨ", "Y"],
                ["Ⓩ", "Z"],
                ["ⓐ", "a"],
                ["ⓑ", "b"],
                ["ⓒ", "c"],
                ["ⓓ", "d"],
                ["ⓔ", "e"],
                ["ⓕ", "f"],
                ["ⓖ", "g"],
                ["ⓗ", "h"],
                ["ⓘ", "i"],
                ["ⓙ", "j"],
                ["ⓚ", "k"],
                ["ⓛ", "l"],
                ["ⓜ", "m"],
                ["ⓝ", "n"],
                ["ⓞ", "o"],
                ["ⓟ", "p"],
                ["ⓠ", "q"],
                ["ⓡ", "r"],
                ["ⓢ", "s"],
                ["ⓣ", "t"],
                ["ⓤ", "u"],
                ["ⓥ", "v"],
                ["ⓦ", "w"],
                ["ⓧ", "x"],
                ["ⓨ", "y"],
                ["ⓩ", "z"],
                ["⓪", "0"]
            ]
        }

        // academic: {
        //     symbols: ["📚", "✍️", "📝", "🔬", "📖", "❓", "📌", "⭐", "🎓"],
        //     keys: [
        //         "read",
        //         "write",
        //         "take notes",
        //         "research",
        //         "review",
        //         "question",
        //         "important",
        //         "insight",
        //         "milestone"
        //     ]
        // },
        // project: {
        //     symbols: ["💡", "📋", "👥", "📊", "🔄", "⚡", "🎨", "🔍", "💪"],
        //     keys: [
        //         "idea",
        //         "planning",
        //         "collaboration",
        //         "review metrics",
        //         "in progress",
        //         "high priority",
        //         "design needed",
        //         "needs research",
        //         "effort required"
        //     ]
        // },
        // health: {
        //     symbols: ["🏃", "🥗", "💪", "😴", "💊", "🧘", "🎯", "❤️", "🩺"],
        //     keys: [
        //         "exercise",
        //         "nutrition",
        //         "strength",
        //         "sleep",
        //         "medication",
        //         "mindfulness",
        //         "goal",
        //         "wellbeing",
        //         "checkup"
        //     ]
        // },
        // writing: {
        //     symbols: ["✍️", "📝", "🔍", "📚", "✂️", "🎭", "🎨", "👥", "📖"],
        //     keys: [
        //         "draft",
        //         "edit",
        //         "research",
        //         "reference",
        //         "cut/revise",
        //         "character work",
        //         "creative",
        //         "feedback",
        //         "review"
        //     ]
        // },
        // coding: {
        //     symbols: ["💡", "🧩", "💻", "🖋️", "🐛", "🔍", "🚀", "🛠️", "✅"],
        //     keys: [
        //         "concept",
        //         "planning/problem breakdown",
        //         "coding",
        //         "documentation",
        //         "debugging",
        //         "code review",
        //         "deploy",
        //         "maintenance",
        //         "completed"
        //     ]
        // },
        // project_management: {
        //     symbols: ["💡", "📅", "🤝", "📈", "⚖️", "🚩", "🔄", "📋", "✅"],
        //     keys: [
        //         "project initiation",
        //         "scheduling",
        //         "team coordination",
        //         "tracking progress",
        //         "resource balancing",
        //         "milestone",
        //         "project updates",
        //         "final review",
        //         "project completion"
        //     ]
        // },
        // scientific_project_management: {
        //     symbols: ["💡", "🔬", "🧪", "📊", "📈", "🔄", "📅", "📉", "✅"],
        //     keys: [
        //         "project concept",
        //         "experimentation",
        //         "data collection",
        //         "data analysis",
        //         "modeling",
        //         "status updates",
        //         "timeline management",
        //         "reporting",
        //         "completion"
        //     ]
        // },
        // engineering_project_management: {
        //     symbols: ["💡", "📐", "⚙️", "📊", "📏", "🚧", "🔍", "📋", "✅"],
        //     keys: [
        //         "idea",
        //         "design phase",
        //         "engineering setup",
        //         "metrics definition",
        //         "specifications",
        //         "construction",
        //         "inspection",
        //         "documentation",
        //         "finished"
        //     ]
        // },
        // flight_planning: {
        //     symbols: ["💡", "🗺️", "📏", "📆", "📍", "⏰", "🛫", "🛬", "✅"],
        //     keys: [
        //         "flight concept",
        //         "route mapping",
        //         "distance planning",
        //         "scheduling",
        //         "waypoints",
        //         "time management",
        //         "takeoff",
        //         "landing",
        //         "flight completed"
        //     ]
        // },
        // scientific_manuscript_writing: {
        //     symbols: ["💡", "📚", "🔍", "✍️", "📈", "📝", "✂️", "📖", "✅"],
        //     keys: [
        //         "idea formulation",
        //         "literature review",
        //         "research",
        //         "writing",
        //         "data visualization",
        //         "drafting",
        //         "revision",
        //         "peer review",
        //         "publication"
        //     ]
        // },
        // default: {
        //     symbols: [
        //         "🚀",
        //         "🎯",
        //         "📅",
        //         "⏳",
        //         "🏁",
        //         "📈",
        //         "✅",
        //         "🐂",
        //         "📉",
        //         "⚠️",
        //         "🚧",
        //         "⏩",
        //         "❎",
        //         "⛔",
        //         "📦",
        //         "❌",
        //     ],
        //     keys: [
        //         "goal: aspirational",
        //         "goal: committed",
        //         "due",
        //         "scheduled",
        //         "start",
        //         "progress",
        //         "done",
        //         "yak-shaving",
        //         "regress",
        //         "attention",
        //         "incomplete",
        //         "forwarded",
        //         "canceled",
        //         "blocked",
        //         "stowed",
        //         "unsuccessful",
        //     ]
        // },
    } as Record<string, FlagMap>
} as const;

export const DEFAULT_CONFIG = {
    daysPast: 15,
    daysFuture: 7,
    ratingMap: 'colors1' as keyof typeof DEFAULT_MAPS.ratings,
} as const;

export const MIN_DAYS_PAST = 1;
export const MIN_DAYS_FUTURE = 1;
export const OUT_OF_BOUNDS = "❗";
export const PLUGIN_NAME = "Focus Tracker";

